
set -g base-index 1
set -g default-terminal "screen-256color"

set-option -g prefix C-a
bind-key C-a last-window

set -g status-left-length 0
set -g status-right-length 451
set -g status-fg "#000000"
set -g status-bg "#77ff00"
set -g window-status-activity-attr bold
set -g pane-border-fg "#444444"
set -g pane-active-border-fg "#55cc00"
set -g message-fg "#111111"
set -g message-bg "#990000"
set -g window-status-format " #I: #W "
set -g window-status-current-format "#[bg=#ffffff,noreverse,bold] #I: #W #[fg=#ffffff,bg=#77ff00,nobold] "
